### ISSUE TITLE
No model 'disk' saved in depth-save.pth 

### ISSUE THREAD

**Issue by ffrivera0** [cvlab-epfl/disk#2]
Hi, thanks for your great work.

I have one error when running `detect.py`, it seems that the `unet.path_down.0.1.1.weight` is missing
```
Missing key(s) in state_dict: "unet.path_down.0.1.1.weight".
```
then I tried to read the `state_dict` and found that only model named 'extractor' exists, will you provide the model named 'disk'?

**Comment by jatentaki** [comment]
It looks to me like your `unets` dependency is on the `master` branch instead of `no_norm_at_start`. The [`.gitmodules`](https://github.com/cvlab-epfl/disk/blob/master/.gitmodules#L4) file specifies the correct branch, so running
```
git clone https://github.com/cvlab-epfl/disk.git --recursive
cd disk
pip install --user -r requirements.txt
```

should install it from the correct branch, but apparently it didn't in your case (or did you install it semi-manually, for instance after forgetting the `--recursive` flag?). Can you try going into `submodules/unets` doing `git checkout no_norm_at_start` and `python setup.py install`?

**Comment by jatentaki** [comment]
By the way, I am not sure why you think that your issue stems from the `disk`/`extractor` stuff. Historically I was using the name `extractor` for saves, which is why `detect.py` [supports both keywords](https://github.com/cvlab-epfl/disk/blob/master/detect.py#L238). This means that your issue should not be related to `disk`/`extractor`.

**Comment by ffrivera0** [comment]
Hi Jatentaki, thank you for your kind reply. 

Yes, I installed `unets` from a different branch. That's the reason why I got the error. For the second question, I think I have a misunderstanding of `disk/extractor`. Thank you again.
