### ISSUE TITLE
backbone of unet

### ISSUE THREAD

**Issue by cvlab-flash** [cvlab-epfl/disk#6]
Hi @ducha-aiki @jatentaki Thanks for your great works! 
i have some questions about the unet backbone you change,
1. why you replace bn by instance normalization， did you do some ablation experiments?
2. why you replace Relu  by PRelu， did you do some ablation experiments?
3. why you replace the two convolutional layers per block by single conv layer， did you do some ablation experiments?
4. whats the meaning of (NL) number of landmarks in your Results on ETH-COLMAP? in other papers i didnt see this, usualy use #Reg Images. # Sparse  Points Track Length, Reproj Error .#Dense Points

Looking forward to your reply! thanks

**Comment by jatentaki** [comment]
1) BN uses batch statistics to normalize tensors. This is usually a rather stable signal with large batch sizes, however if batch size is small (say 2 images), the normalization constant becomes almost stochastic: in other words, an image of a cat will be interpreted completely differently if it happened to be in a batch with another image of a cat, of a dog, etc. I have no numbers to present, but I have done experiments like that before and Unets basically do not work with BN and small batch sizes. Since DISK itself has huge memory requirements, I work with very small batch sizes (1-2) and therefore I use instance normalization to avoid this effect.
2) In my experience PReLU outperforms ReLU but I haven't done any ablations in the context of DISK.
3) To reduce the memory footprint of the network and make it learn faster, speeding up development time. I have done an experiment with a "fat" unet with DISK and having two conv layers per block did give a performance improvement (but it was a while before arriving at the final formulation for DISK, so the benchmark entries are with "lean" and therefore potentially suboptimal unets).
4) By landmarks we mean 3d points triangulated by the SfM procedure. I believe some papers indeed call it `sparse points`. We do not report dense points because they come from patch-matching which is a problem almost completely orthogonal to local features.

**Comment by cvlab-flash** [comment]
hi, @jatentaki, thanks for your reply
as you note in readme that training in low gpu mode may take on the order of 2 weeks! will you add multi-gpu training or distributed trainning code in future? it may be more easy for people to reproduce the results without V100 gpus

Looking forward to your reply! thanks

**Comment by jatentaki** [comment]
I don't think I have the time to implement multi-gpu training, but I'll be happy to accept a PR
